/**
 * Wanderlust seed data — fictional demo properties only.
 * Image URLs use picsum.photos placeholder service (no real hotel imagery).
 */
import { ROLES } from '../utils/constants.js';

export const DEMO_PASSWORD = 'password123';
export const img = (seed, w = 1200, h = 800) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const USERS = [
  { name: 'Admin Wander', email: 'admin123@gmail.com', password: 'Admin@123', role: ROLES.ADMIN, verified: true },
  { name: 'Aarav Sharma', email: 'owner@wanderlust.dev', role: ROLES.OWNER, verified: true },
  { name: 'Meera Iyer', email: 'meera.owner@wanderlust.dev', role: ROLES.OWNER, verified: true },
  { name: 'Vikram Rathore', email: 'vikram.owner@wanderlust.dev', role: ROLES.OWNER, verified: true },
  { name: 'Ananya Desai', email: 'ananya.owner@wanderlust.dev', role: ROLES.OWNER, verified: true },
  { name: 'Rahul Menon', email: 'rahul.owner@wanderlust.dev', role: ROLES.OWNER, verified: true },
  { name: 'Ishita Bose', email: 'ishita.owner@wanderlust.dev', role: ROLES.OWNER, verified: true },
  { name: 'Arjun Pillai', email: 'arjun.owner@wanderlust.dev', role: ROLES.OWNER, verified: true },
  { name: 'Neha Kulkarni', email: 'neha.owner@wanderlust.dev', role: ROLES.OWNER, verified: true },
  { name: 'Dev Chauhan', email: 'dev.owner@wanderlust.dev', role: ROLES.OWNER, verified: true },
  { name: 'Riya Malhotra', email: 'riya.owner@wanderlust.dev', role: ROLES.OWNER, verified: true },
  { name: 'Kabir Verma', email: 'guest@wanderlust.dev', role: ROLES.CUSTOMER, verified: true },
  { name: 'Sana Kapoor', email: 'sana@example.com', role: ROLES.CUSTOMER, verified: true },
  { name: 'Rohit Nair', email: 'rohit@example.com', role: ROLES.CUSTOMER, verified: true },
  { name: 'Priya Singh', email: 'priya@example.com', role: ROLES.CUSTOMER, verified: true },
];

export const HOTEL_DEFS = [
  {
    owner: 'owner@wanderlust.dev',
    name: 'The Coral Cove Resort',
    tagline: 'Beachfront luxury in North Goa',
    city: 'North Goa', state: 'Goa', postalCode: '403515',
    location: [73.7503, 15.6027],
    propertyType: 'resort', starRating: 5, featured: true,
    amenities: ['wifi', 'pool', 'spa', 'restaurant', 'bar', 'air-conditioning', 'parking', 'beachfront', 'airport-shuttle', 'room-service'],
    policies: { freeCancellationHours: 72, cancellationFeePercent: 15, checkInTime: '14:00', checkOutTime: '11:00' },
    description: 'A stunning beachfront resort on the shores of North Goa. Ocean-view suites, an infinity pool overlooking the Arabian Sea, award-winning seafood dining and a world-class spa make every stay unforgettable.',
    rooms: [
      { name: 'Ocean View Suite', roomType: 'suite', price: 9500, adults: 3, children: 1, bedType: 'king', totalUnits: 6, weekendMarkupPercent: 12, amenities: ['wifi', 'air-conditioning', 'balcony'] },
      { name: 'Deluxe Seaview Room', roomType: 'deluxe', price: 6200, adults: 2, children: 1, bedType: 'queen', totalUnits: 14, weekendMarkupPercent: 10, amenities: ['wifi', 'air-conditioning'] },
      { name: 'Poolside Cottage', roomType: 'cottage', price: 7800, adults: 2, children: 0, bedType: 'king', totalUnits: 8, weekendMarkupPercent: 10, amenities: ['wifi', 'pool', 'air-conditioning'] },
    ],
  },
  {
    owner: 'owner@wanderlust.dev',
    name: 'Himalayan Pine Retreat',
    tagline: 'Snow-capped views in Old Manali',
    city: 'Manali', state: 'Himachal Pradesh', postalCode: '175131',
    location: [77.1734, 32.2432],
    propertyType: 'hotel', starRating: 4, featured: true,
    amenities: ['wifi', 'restaurant', 'parking', 'fireplace', 'mountain-view', 'laundry', 'room-service'],
    policies: { freeCancellationHours: 48, cancellationFeePercent: 25, checkInTime: '13:00', checkOutTime: '11:00' },
    description: 'A warm pinewood retreat nestled in the mountains of Old Manali. Cosy rooms with roaring fireplaces, panoramic valley views and easy access to Solang Valley and Hadimba Temple.',
    rooms: [
      { name: 'Valley View Deluxe', roomType: 'deluxe', price: 4200, adults: 2, children: 1, bedType: 'king', totalUnits: 10, weekendMarkupPercent: 15, amenities: ['wifi', 'fireplace', 'mountain-view'] },
      { name: 'Alpine Standard Room', roomType: 'standard', price: 2400, adults: 2, children: 0, bedType: 'double', totalUnits: 16, amenities: ['wifi', 'heater'] },
      { name: 'Pinewood Family Suite', roomType: 'family', price: 6800, adults: 4, children: 2, bedType: 'king', totalUnits: 5, amenities: ['wifi', 'kitchen', 'fireplace'] },
    ],
  },
  {
    owner: 'owner@wanderlust.dev',
    name: 'Amber Heritage Haveli',
    tagline: 'A royal Rajasthani experience',
    city: 'Jaipur', state: 'Rajasthan', postalCode: '302001',
    location: [75.7873, 26.9124],
    propertyType: 'hotel', starRating: 5, featured: false,
    amenities: ['wifi', 'pool', 'restaurant', 'air-conditioning', 'parking', 'room-service', 'laundry'],
    policies: { freeCancellationHours: 48, cancellationFeePercent: 25, checkInTime: '13:00', checkOutTime: '11:00' },
    description: 'Dating back to 1925, Amber Heritage Haveli blends Rajputana grandeur with modern comfort. Intricate frescoes, lush courtyards and rooftop dining overlooking the Pink City.',
    rooms: [
      { name: 'Maharaja Suite', roomType: 'suite', price: 12500, adults: 2, children: 1, bedType: 'king', totalUnits: 3, amenities: ['wifi', 'air-conditioning'] },
      { name: 'Courtyard Deluxe', roomType: 'deluxe', price: 7400, adults: 2, children: 1, bedType: 'queen', totalUnits: 12, amenities: ['wifi', 'air-conditioning'] },
      { name: 'Heritage Room', roomType: 'standard', price: 4600, adults: 2, children: 0, bedType: 'double', totalUnits: 18, amenities: ['wifi', 'air-conditioning'] },
    ],
  },
  {
    owner: 'meera.owner@wanderlust.dev',
    name: 'Lake Palace Retreat',
    tagline: 'Mirror-water serenity in Udaipur',
    city: 'Udaipur', state: 'Rajasthan', postalCode: '313001',
    location: [73.6802, 24.5714],
    propertyType: 'resort', starRating: 5, featured: true,
    amenities: ['wifi', 'pool', 'spa', 'restaurant', 'bar', 'air-conditioning', 'boat-rides', 'parking'],
    policies: { freeCancellationHours: 72, cancellationFeePercent: 15, checkInTime: '14:00', checkOutTime: '11:00' },
    description: 'Floating gardens, lake-view terraces and palatial suites. This resort sits right on the banks of Lake Pichola with private boat transfers to the city palace.',
    rooms: [
      { name: 'Lake View Palace Room', roomType: 'deluxe', price: 9800, adults: 2, children: 1, bedType: 'king', totalUnits: 8, amenities: ['wifi', 'air-conditioning', 'balcony'] },
      { name: 'Mahal Suite', roomType: 'suite', price: 16500, adults: 3, children: 1, bedType: 'king', totalUnits: 4, amenities: ['wifi', 'air-conditioning', 'jacuzzi'] },
      { name: 'Garden Cottage', roomType: 'cottage', price: 7200, adults: 2, children: 0, bedType: 'queen', totalUnits: 6, amenities: ['wifi', 'air-conditioning'] },
    ],
  },
  {
    owner: 'meera.owner@wanderlust.dev',
    name: 'Mist & Spice Plantation Stay',
    tagline: 'Coffee-scented calm in Coorg',
    city: 'Coorg', state: 'Karnataka', postalCode: '571201',
    location: [75.7904, 12.3375],
    propertyType: 'homestay', starRating: 4, featured: false,
    amenities: ['wifi', 'kitchen', 'breakfast', 'parking', 'mountain-view', 'pets-allowed', 'fireplace'],
    policies: { freeCancellationHours: 36, cancellationFeePercent: 30, checkInTime: '13:00', checkOutTime: '11:00' },
    description: 'Wake up to the aroma of freshly roasted coffee on a working plantation. Guided estate walks, organic farm-to-table meals and misty morning treks.',
    rooms: [
      { name: 'Estate Bungalow', roomType: 'villa', price: 5900, adults: 4, children: 2, bedType: 'king', totalUnits: 3, amenities: ['wifi', 'kitchen', 'fireplace'] },
      { name: 'Planter Room', roomType: 'standard', price: 3100, adults: 2, children: 1, bedType: 'double', totalUnits: 8, amenities: ['wifi', 'breakfast'] },
      { name: 'Coffee Grove Deluxe', roomType: 'deluxe', price: 4200, adults: 2, children: 1, bedType: 'queen', totalUnits: 6, amenities: ['wifi', 'mountain-view'] },
    ],
  },
  {
    owner: 'meera.owner@wanderlust.dev',
    name: 'Ganga Steps Riverside Inn',
    tagline: 'Yoga, rafting and riverside peace',
    city: 'Rishikesh', state: 'Uttarakhand', postalCode: '249201',
    location: [78.2834, 30.0869],
    propertyType: 'guesthouse', starRating: 3, featured: false,
    amenities: ['wifi', 'restaurant', 'yoga', 'parking', 'mountain-view', 'laundry'],
    policies: { freeCancellationHours: 24, cancellationFeePercent: 35, checkInTime: '12:00', checkOutTime: '10:00' },
    description: 'Steps from the Ganga with sunrise yoga decks, organic Kirtan meals and easy access to rafting camps and the Beatles Ashram.',
    rooms: [
      { name: 'Riverside Deluxe', roomType: 'deluxe', price: 2800, adults: 2, children: 1, bedType: 'double', totalUnits: 8, amenities: ['wifi', 'balcony'] },
      { name: 'Ganga View Room', roomType: 'standard', price: 1800, adults: 2, children: 0, bedType: 'single', totalUnits: 14, amenities: ['wifi'] },
      { name: 'Yoga Retreat Family Room', roomType: 'family', price: 3900, adults: 4, children: 2, bedType: 'twin', totalUnits: 5, amenities: ['wifi', 'yoga'] },
    ],
  },
  {
    owner: 'meera.owner@wanderlust.dev',
    name: 'Queen of Hills Heritage Hotel',
    tagline: 'Victorian charm with tea-garden views',
    city: 'Darjeeling', state: 'West Bengal', postalCode: '734101',
    location: [88.2627, 27.0410],
    propertyType: 'hotel', starRating: 4, featured: false,
    amenities: ['wifi', 'restaurant', 'fireplace', 'parking', 'mountain-view', 'laundry', 'bar'],
    policies: { freeCancellationHours: 48, cancellationFeePercent: 25, checkInTime: '13:00', checkOutTime: '11:00' },
    description: 'A colonial-era hotel overlooking tea gardens with Kanchenjunga sunrises from the veranda. Antique furniture, high tea and a cosy reading room.',
    rooms: [
      { name: 'Kanchenjunga View Room', roomType: 'deluxe', price: 4800, adults: 2, children: 1, bedType: 'king', totalUnits: 6, amenities: ['wifi', 'fireplace', 'mountain-view'] },
      { name: 'Colonial Standard', roomType: 'standard', price: 2600, adults: 2, children: 0, bedType: 'double', totalUnits: 12, amenities: ['wifi'] },
      { name: 'Tea Estate Suite', roomType: 'suite', price: 7800, adults: 3, children: 1, bedType: 'king', totalUnits: 3, amenities: ['wifi', 'fireplace'] },
    ],
  },
  {
    owner: 'meera.owner@wanderlust.dev',
    name: 'Backwater Houseboat Retreat',
    tagline: 'Slow mornings on the Alleppey canals',
    city: 'Alleppey', state: 'Kerala', postalCode: '688001',
    location: [76.3380, 9.4981],
    propertyType: 'resort', starRating: 4, featured: true,
    amenities: ['wifi', 'restaurant', 'air-conditioning', 'boat-rides', 'breakfast'],
    policies: { freeCancellationHours: 72, cancellationFeePercent: 20, checkInTime: '12:00', checkOutTime: '09:00' },
    description: 'Traditional kettuvallam houseboats and canal-side cottages in the heart of Kerala backwaters. Fresh seafood, toddy tastings and lake cruises.',
    rooms: [
      { name: 'Premium Houseboat', roomType: 'suite', price: 8200, adults: 2, children: 1, bedType: 'queen', totalUnits: 5, amenities: ['wifi', 'air-conditioning'] },
      { name: 'Canal Cottage', roomType: 'cottage', price: 4600, adults: 2, children: 0, bedType: 'double', totalUnits: 6, amenities: ['air-conditioning'] },
      { name: 'Lotus Deluxe Room', roomType: 'deluxe', price: 3800, adults: 2, children: 1, bedType: 'queen', totalUnits: 10, amenities: ['wifi', 'air-conditioning'] },
    ],
  },
  {
    owner: 'meera.owner@wanderlust.dev',
    name: 'French Quarter Heritage Villa',
    tagline: 'Colonial pastels in Pondicherry',
    city: 'Pondicherry', state: 'Puducherry', postalCode: '605001',
    location: [79.8105, 11.9416],
    propertyType: 'villa', starRating: 4, featured: false,
    amenities: ['wifi', 'kitchen', 'breakfast', 'air-conditioning', 'parking'],
    policies: { freeCancellationHours: 48, cancellationFeePercent: 25, checkInTime: '13:00', checkOutTime: '11:00' },
    description: 'A restored French-colonial villa in the White Town, minutes from the promenade. Pastel walls, bougainvillea courtyards and quiet book nooks.',
    rooms: [
      { name: 'Courtyard Room', roomType: 'standard', price: 3200, adults: 2, children: 0, bedType: 'double', totalUnits: 6, amenities: ['wifi', 'air-conditioning'] },
      { name: 'Pastel Suite', roomType: 'suite', price: 6400, adults: 2, children: 1, bedType: 'king', totalUnits: 3, amenities: ['wifi', 'air-conditioning'] },
    ],
  },
  {
    owner: 'meera.owner@wanderlust.dev',
    name: 'Mist Valley Tea Estate Resort',
    tagline: 'Rolling tea hills of Munnar',
    city: 'Munnar', state: 'Kerala', postalCode: '685612',
    location: [77.0653, 10.0889],
    propertyType: 'resort', starRating: 5, featured: false,
    amenities: ['wifi', 'pool', 'spa', 'restaurant', 'fireplace', 'mountain-view', 'parking'],
    policies: { freeCancellationHours: 48, cancellationFeePercent: 20, checkInTime: '13:00', checkOutTime: '11:00' },
    description: 'Perched on a working tea estate with an infinity pool looking across endless emerald hills. Plantation treks, tea tastings and foggy fire-side evenings.',
    rooms: [
      { name: 'Tea Terrace Suite', roomType: 'suite', price: 9800, adults: 2, children: 1, bedType: 'king', totalUnits: 4, amenities: ['wifi', 'mountain-view', 'fireplace'] },
      { name: 'Plantation Deluxe', roomType: 'deluxe', price: 5900, adults: 2, children: 1, bedType: 'queen', totalUnits: 10, amenities: ['wifi', 'mountain-view'] },
    ],
  },
  {
    owner: 'meera.owner@wanderlust.dev',
    name: 'Cliffside Kayal Resort',
    tagline: 'Sunset cliffs above the Arabian Sea',
    city: 'Varkala', state: 'Kerala', postalCode: '695141',
    location: [76.7168, 8.7377],
    propertyType: 'resort', starRating: 4, featured: false,
    amenities: ['wifi', 'pool', 'restaurant', 'air-conditioning', 'beachfront', 'yoga', 'parking'],
    policies: { freeCancellationHours: 48, cancellationFeePercent: 25, checkInTime: '13:00', checkOutTime: '11:00' },
    description: 'Clifftop cottages with panoramic ocean views, a mineral-spring pool and coastal Kerala cuisine. Steps from Varkala beach and the Papanasam cliff walk.',
    rooms: [
      { name: 'Cliff Sunset Room', roomType: 'deluxe', price: 5400, adults: 2, children: 1, bedType: 'queen', totalUnits: 8, amenities: ['wifi', 'air-conditioning', 'balcony'] },
      { name: 'Ocean View Cottage', roomType: 'cottage', price: 7000, adults: 2, children: 0, bedType: 'king', totalUnits: 4, amenities: ['wifi', 'air-conditioning'] },
      { name: 'Yoga Pavilion Standard', roomType: 'standard', price: 2900, adults: 2, children: 0, bedType: 'double', totalUnits: 10, amenities: ['wifi'] },
    ],
  },
  {
    owner: 'owner@wanderlust.dev',
    name: 'Khajuraho Starlight Desert Camp',
    tagline: 'Sleep under a billion stars',
    city: 'Jaisalmer', state: 'Rajasthan', postalCode: '345001',
    location: [70.9036, 26.9157],
    propertyType: 'resort', starRating: 5, featured: true,
    amenities: ['wifi', 'restaurant', 'bar', 'parking', 'camel-safari', 'breakfast'],
    policies: { freeCancellationHours: 72, cancellationFeePercent: 20, checkInTime: '13:00', checkOutTime: '11:00' },
    description: 'Luxury Swiss tents in the Thar desert with stargazing decks, camel safaris and folk music around the campfire under a blanket of stars.',
    rooms: [
      { name: 'Luxury Swiss Tent', roomType: 'suite', price: 6800, adults: 2, children: 2, bedType: 'king', totalUnits: 12, weekendMarkupPercent: 20, amenities: ['wifi', 'breakfast'] },
      { name: 'Desert Deluxe Tent', roomType: 'deluxe', price: 4200, adults: 2, children: 1, bedType: 'queen', totalUnits: 18, amenities: ['breakfast'] },
      { name: 'Haveli Family Room', roomType: 'family', price: 3600, adults: 4, children: 2, bedType: 'twin', totalUnits: 6, amenities: ['wifi', 'breakfast'] },
    ],
  },
  {
    owner: 'vikram.owner@wanderlust.dev',
    name: 'Rann Vista Bhunga',
    tagline: 'Mud-and-mirror cottages on the white salt desert',
    city: 'Bhuj', state: 'Gujarat', postalCode: '370001',
    location: [69.6669, 23.2419],
    propertyType: 'resort', starRating: 4, featured: false,
    amenities: ['wifi', 'restaurant', 'parking', 'breakfast', 'cultural-shows', 'air-conditioning'],
    policies: { freeCancellationHours: 48, cancellationFeePercent: 20, checkInTime: '12:00', checkOutTime: '10:00' },
    description: 'Traditional Kutchi bhungas with mirror-work interiors on the edge of the White Rann. Folk evenings, craft village walks and sunrise over the salt flats.',
    rooms: [
      { name: 'Rann View Bhunga', roomType: 'deluxe', price: 4800, adults: 2, children: 1, bedType: 'queen', totalUnits: 8, weekendMarkupPercent: 15, amenities: ['wifi', 'air-conditioning', 'breakfast'] },
      { name: 'Family Bhunga', roomType: 'family', price: 6200, adults: 4, children: 2, bedType: 'twin', totalUnits: 5, amenities: ['wifi', 'air-conditioning'] },
      { name: 'Standard Cottage', roomType: 'standard', price: 2600, adults: 2, children: 0, bedType: 'double', totalUnits: 10, amenities: ['wifi'] },
    ],
  },
  {
    owner: 'ananya.owner@wanderlust.dev',
    name: 'Tea Trail Bungalow Munnar',
    tagline: 'Wake up inside a working tea estate',
    city: 'Munnar', state: 'Kerala', postalCode: '685612',
    location: [77.0832, 10.0889],
    propertyType: 'homestay', starRating: 4, featured: true,
    amenities: ['wifi', 'breakfast', 'fireplace', 'mountain-view', 'plantation-walk', 'parking'],
    policies: { freeCancellationHours: 48, cancellationFeePercent: 20, checkInTime: '13:00', checkOutTime: '11:00' },
    description: 'A colonial-era planter bungalow wrapped in emerald tea rows. Guided estate walks, factory visits and Kerala breakfasts on the veranda.',
    rooms: [
      { name: 'Planter Suite', roomType: 'suite', price: 7400, adults: 2, children: 1, bedType: 'king', totalUnits: 3, weekendMarkupPercent: 10, amenities: ['wifi', 'fireplace', 'mountain-view'] },
      { name: 'Estate Deluxe', roomType: 'deluxe', price: 4600, adults: 2, children: 0, bedType: 'queen', totalUnits: 6, amenities: ['wifi', 'mountain-view'] },
      { name: 'Garden Standard', roomType: 'standard', price: 2800, adults: 2, children: 0, bedType: 'double', totalUnits: 8, amenities: ['wifi'] },
    ],
  },
  {
    owner: 'rahul.owner@wanderlust.dev',
    name: 'Zanskar Riverside Camp',
    tagline: 'Luxury camping where two rivers meet',
    city: 'Leh', state: 'Ladakh', postalCode: '194101',
    location: [77.5771, 34.1526],
    propertyType: 'cottage', starRating: 4, featured: false,
    amenities: ['wifi', 'restaurant', 'bonfire', 'breakfast', 'oxygen-support', 'parking'],
    policies: { freeCancellationHours: 72, cancellationFeePercent: 25, checkInTime: '12:00', checkOutTime: '10:00' },
    description: 'Heated safari tents on the Indus riverbank with views of snow ridges. Bonfire dinners, monastery day-trips and high-altitude comfort.',
    rooms: [
      { name: 'Riverside Luxury Tent', roomType: 'suite', price: 7900, adults: 2, children: 1, bedType: 'king', totalUnits: 8, weekendMarkupPercent: 0, amenities: ['wifi', 'breakfast', 'heater'] },
      { name: 'Base Camp Deluxe', roomType: 'deluxe', price: 5200, adults: 2, children: 0, bedType: 'queen', totalUnits: 12, amenities: ['breakfast', 'heater'] },
    ],
  },
  {
    owner: 'ishita.owner@wanderlust.dev',
    name: 'Konkan Spice Homestay',
    tagline: 'Beach walks and home-cooked Malvani thalis',
    city: 'Gokarna', state: 'Karnataka', postalCode: '581326',
    location: [74.3163, 14.5469],
    propertyType: 'homestay', starRating: 3, featured: false,
    amenities: ['wifi', 'breakfast', 'restaurant', 'air-conditioning', 'beachfront', 'parking'],
    policies: { freeCancellationHours: 24, cancellationFeePercent: 15, checkInTime: '12:00', checkOutTime: '10:00' },
    description: 'A family-run spice-farm homestay ten minutes from Om Beach. Malvani seafood, courtyard swings and hammocks under the mango trees.',
    rooms: [
      { name: 'Spice Garden Room', roomType: 'standard', price: 2200, adults: 2, children: 0, bedType: 'double', totalUnits: 8, amenities: ['wifi', 'air-conditioning'] },
      { name: 'Beachside Deluxe', roomType: 'deluxe', price: 3400, adults: 2, children: 1, bedType: 'queen', totalUnits: 5, weekendMarkupPercent: 12, amenities: ['wifi', 'air-conditioning', 'balcony'] },
      { name: 'Mango Grove Family Room', roomType: 'family', price: 4200, adults: 4, children: 2, bedType: 'twin', totalUnits: 3, amenities: ['wifi', 'air-conditioning'] },
    ],
  },
  {
    owner: 'arjun.owner@wanderlust.dev',
    name: 'Bikaner Haveli Suites',
    tagline: 'A 200-year-old haveli in the old city lanes',
    city: 'Bikaner', state: 'Rajasthan', postalCode: '334001',
    location: [73.3097, 28.0229],
    propertyType: 'hotel', starRating: 4, featured: true,
    amenities: ['wifi', 'restaurant', 'rooftop-dining', 'air-conditioning', 'parking', 'heritage-walk'],
    policies: { freeCancellationHours: 48, cancellationFeePercent: 20, checkInTime: '12:00', checkOutTime: '11:00' },
    description: 'Carved sandstone courtyards, frescoed suites and rooftop dinners facing Junagarh Fort. A living piece of Marwar heritage.',
    rooms: [
      { name: 'Fresco Suite', roomType: 'suite', price: 6900, adults: 2, children: 2, bedType: 'king', totalUnits: 4, weekendMarkupPercent: 10, amenities: ['wifi', 'air-conditioning', 'breakfast'] },
      { name: 'Courtyard Deluxe', roomType: 'deluxe', price: 4400, adults: 2, children: 1, bedType: 'queen', totalUnits: 8, amenities: ['wifi', 'air-conditioning'] },
      { name: 'Heritage Standard', roomType: 'standard', price: 2500, adults: 2, children: 0, bedType: 'double', totalUnits: 10, amenities: ['wifi', 'air-conditioning'] },
    ],
  },
  {
    owner: 'neha.owner@wanderlust.dev',
    name: 'Corbett Jungle Lodge',
    tagline: 'Tiger country, right outside your window',
    city: 'Jim Corbett', state: 'Uttarakhand', postalCode: '244714',
    location: [78.7708, 29.5300],
    propertyType: 'resort', starRating: 4, featured: false,
    amenities: ['wifi', 'restaurant', 'safari-booking', 'pool', 'air-conditioning', 'parking', 'bonfire'],
    policies: { freeCancellationHours: 72, cancellationFeePercent: 25, checkInTime: '12:00', checkOutTime: '10:00' },
    description: 'Buffer-zone lodge with jeep safaris at dawn, evening bird walks and lantern-lit dinners under the sal trees.',
    rooms: [
      { name: 'Sal Forest Villa', roomType: 'suite', price: 8200, adults: 2, children: 2, bedType: 'king', totalUnits: 6, weekendMarkupPercent: 18, amenities: ['wifi', 'air-conditioning', 'pool-access'] },
      { name: 'Jungle Deluxe', roomType: 'deluxe', price: 5600, adults: 2, children: 1, bedType: 'queen', totalUnits: 10, amenities: ['wifi', 'air-conditioning'] },
      { name: 'Tusker Family Room', roomType: 'family', price: 4800, adults: 4, children: 2, bedType: 'twin', totalUnits: 6, amenities: ['wifi', 'air-conditioning'] },
    ],
  },
  {
    owner: 'dev.owner@wanderlust.dev',
    name: 'Pondicherry Beach House',
    tagline: 'French-quarter mornings by the Bay of Bengal',
    city: 'Puducherry', state: 'Puducherry', postalCode: '605001',
    location: [79.8083, 11.9416],
    propertyType: 'villa', starRating: 4, featured: true,
    amenities: ['wifi', 'pool', 'breakfast', 'air-conditioning', 'beachfront', 'bicycles', 'parking'],
    policies: { freeCancellationHours: 48, cancellationFeePercent: 15, checkInTime: '14:00', checkOutTime: '11:00' },
    description: 'A whitewashed villa on Promenade Beach with a private courtyard pool, café-style breakfasts and bicycles to explore the French quarter.',
    rooms: [
      { name: 'Promenade Suite', roomType: 'suite', price: 7600, adults: 2, children: 1, bedType: 'king', totalUnits: 3, weekendMarkupPercent: 15, amenities: ['wifi', 'air-conditioning', 'balcony'] },
      { name: 'Courtyard Deluxe', roomType: 'deluxe', price: 5100, adults: 2, children: 0, bedType: 'queen', totalUnits: 5, amenities: ['wifi', 'air-conditioning', 'pool-access'] },
      { name: 'Beach Standard', roomType: 'standard', price: 3300, adults: 2, children: 0, bedType: 'double', totalUnits: 7, amenities: ['wifi', 'air-conditioning'] },
    ],
  },
  {
    owner: 'riya.owner@wanderlust.dev',
    name: 'Shillong Cloud Homestay',
    tagline: 'Pine hills, waterfalls and rain-washed skies',
    city: 'Shillong', state: 'Meghalaya', postalCode: '793001',
    location: [91.8834, 25.5788],
    propertyType: 'homestay', starRating: 3, featured: false,
    amenities: ['wifi', 'breakfast', 'mountain-view', 'fireplace', 'parking', 'laundry'],
    policies: { freeCancellationHours: 24, cancellationFeePercent: 15, checkInTime: '13:00', checkOutTime: '11:00' },
    description: 'A wooden Khasi-style homestay above Umiam lake views. Bonfire evenings, Shillong Peak sunrise runs and home-baked goodies.',
    rooms: [
      { name: 'Cloud View Deluxe', roomType: 'deluxe', price: 3200, adults: 2, children: 1, bedType: 'queen', totalUnits: 6, weekendMarkupPercent: 10, amenities: ['wifi', 'fireplace', 'mountain-view'] },
      { name: 'Pine Standard', roomType: 'standard', price: 2000, adults: 2, children: 0, bedType: 'double', totalUnits: 9, amenities: ['wifi'] },
      { name: 'Lakeview Family Room', roomType: 'family', price: 4500, adults: 4, children: 2, bedType: 'twin', totalUnits: 4, amenities: ['wifi', 'mountain-view'] },
    ],
  },
];

// Distribute every hotel evenly across the demo owners (2 properties per owner)
// so a fresh deployment already has 10 owners × 2 hotels with zero manual setup.
const OWNER_POOL = USERS.filter((u) => u.role === ROLES.OWNER).map((u) => u.email);
HOTEL_DEFS.forEach((def, i) => { def.owner = OWNER_POOL[i % OWNER_POOL.length]; });

export const COUPONS = [
  { code: 'WELCOME10', description: '10% off your first booking', discountType: 'percent', discountValue: 10, minimumBookingAmount: 2000, maximumDiscount: 1500, startDate: new Date('2024-01-01'), endDate: new Date('2030-12-31'), usageLimit: 0, perUserLimit: 1, active: true },
  { code: 'FLAT500', description: 'Flat ₹500 off stays above ₹5,000', discountType: 'fixed', discountValue: 500, minimumBookingAmount: 5000, maximumDiscount: 500, startDate: new Date('2024-01-01'), endDate: new Date('2030-12-31'), usageLimit: 0, perUserLimit: 2, active: true },
  { code: 'SUMMER25', description: '25% off summer escapes (max ₹2,500)', discountType: 'percent', discountValue: 25, minimumBookingAmount: 3000, maximumDiscount: 2500, startDate: new Date('2026-03-01'), endDate: new Date('2026-08-31'), usageLimit: 500, perUserLimit: 1, active: true },
  { code: 'LUXURYX', description: '₹2,000 off luxury stays', discountType: 'fixed', discountValue: 2000, minimumBookingAmount: 15000, maximumDiscount: 2000, startDate: new Date('2026-01-01'), endDate: new Date('2026-12-31'), usageLimit: 100, perUserLimit: 1, active: true },
  { code: 'OFF10', description: 'Inactive sample coupon', discountType: 'percent', discountValue: 10, minimumBookingAmount: 0, maximumDiscount: 0, startDate: new Date('2024-01-01'), endDate: new Date('2030-12-31'), usageLimit: 0, perUserLimit: 1, active: false },
];